version: '3.1'
services:
  auth:
    image: node:alpine
    restart: unless-stopped
    command: "node /app/main.js"
    ports:
      - 8080:8080
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./build/:/app
